begin;

create table if not exists public.albums (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null,
  year integer,
  discos integer not null default 1,
  cover text not null default '',
  audio_url text not null default '',
  description text not null default '',
  tracklist jsonb not null default '[]'::jsonb,
  track_audio jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint albums_title_length check (char_length(btrim(title)) between 1 and 200),
  constraint albums_artist_length check (char_length(btrim(artist)) between 1 and 200),
  constraint albums_description_length check (char_length(description) <= 5000),
  constraint albums_year_range check (year is null or year between 1900 and 2200),
  constraint albums_discos_range check (discos between 1 and 10),
  constraint albums_tracklist_array check (jsonb_typeof(tracklist) = 'array'),
  constraint albums_track_audio_object check (jsonb_typeof(track_audio) = 'object')
);

alter table public.albums add column if not exists track_audio jsonb not null default '{}'::jsonb;
alter table public.albums add column if not exists title text not null default '';
alter table public.albums add column if not exists artist text not null default '';
alter table public.albums add column if not exists year integer;
alter table public.albums add column if not exists discos integer not null default 1;
alter table public.albums add column if not exists cover text not null default '';
alter table public.albums add column if not exists audio_url text not null default '';
alter table public.albums add column if not exists description text not null default '';
alter table public.albums add column if not exists tracklist jsonb not null default '[]'::jsonb;
alter table public.albums add column if not exists created_at timestamptz not null default now();
alter table public.albums add column if not exists updated_at timestamptz not null default now();

create table if not exists public.admin_sessions (
  token_hash text primary key,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint admin_sessions_token_hash_format check (token_hash ~ '^[a-f0-9]{64}$')
);
create index if not exists admin_sessions_expires_at_idx on public.admin_sessions (expires_at);

create table if not exists public.admin_login_attempts (
  id bigint generated by default as identity primary key,
  client_key text not null,
  attempted_at timestamptz not null default now(),
  constraint admin_login_attempts_key_format check (client_key ~ '^[a-f0-9]{64}$')
);
create index if not exists admin_login_attempts_lookup_idx on public.admin_login_attempts (client_key, attempted_at);

update public.albums set updated_at = now() where updated_at is null;

do $$
begin
  if not exists (select 1 from pg_constraint where conrelid = 'public.albums'::regclass and conname = 'albums_title_length') then
    alter table public.albums add constraint albums_title_length check (char_length(btrim(title)) between 1 and 200) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.albums'::regclass and conname = 'albums_artist_length') then
    alter table public.albums add constraint albums_artist_length check (char_length(btrim(artist)) between 1 and 200) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.albums'::regclass and conname = 'albums_description_length') then
    alter table public.albums add constraint albums_description_length check (char_length(description) <= 5000) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.albums'::regclass and conname = 'albums_year_range') then
    alter table public.albums add constraint albums_year_range check (year is null or year between 1900 and 2200) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.albums'::regclass and conname = 'albums_discos_range') then
    alter table public.albums add constraint albums_discos_range check (discos between 1 and 10) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.albums'::regclass and conname = 'albums_tracklist_array') then
    alter table public.albums add constraint albums_tracklist_array check (jsonb_typeof(tracklist) = 'array') not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.albums'::regclass and conname = 'albums_track_audio_object') then
    alter table public.albums add constraint albums_track_audio_object check (jsonb_typeof(track_audio) = 'object') not valid;
  end if;
end $$;

alter table public.albums validate constraint albums_title_length;
alter table public.albums validate constraint albums_artist_length;
alter table public.albums validate constraint albums_description_length;
alter table public.albums validate constraint albums_year_range;
alter table public.albums validate constraint albums_discos_range;
alter table public.albums validate constraint albums_tracklist_array;
alter table public.albums validate constraint albums_track_audio_object;

alter table public.albums enable row level security;
alter table public.albums force row level security;
alter table public.admin_sessions enable row level security;
alter table public.admin_sessions force row level security;
alter table public.admin_login_attempts enable row level security;
alter table public.admin_login_attempts force row level security;

do $$
declare policy_row record;
begin
  for policy_row in select policyname from pg_policies where schemaname = 'public' and tablename = 'albums'
  loop
    execute format('drop policy if exists %I on public.albums', policy_row.policyname);
  end loop;
  if exists(select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects') then
    raise exception 'Existing storage.objects policies require manual review; migration does not delete policies for other buckets';
  end if;
end $$;

revoke all on public.albums from anon, authenticated;
revoke all on public.admin_sessions from anon, authenticated;
revoke all on public.admin_login_attempts from anon, authenticated;
do $$
begin
  if to_regclass('public.albums_id_seq') is not null then
    execute 'revoke all on sequence public.albums_id_seq from anon, authenticated';
  end if;
end $$;

create or replace function public.consume_admin_login_attempt(p_client_key text)
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare attempt_count integer;
begin
  if p_client_key !~ '^[a-f0-9]{64}$' then
    raise exception 'invalid client key';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(p_client_key, 0));
  delete from public.admin_login_attempts where attempted_at < now() - interval '15 minutes';
  insert into public.admin_login_attempts (client_key) values (p_client_key);
  select count(*) into attempt_count
    from public.admin_login_attempts
    where client_key = p_client_key and attempted_at >= now() - interval '15 minutes';
  return attempt_count;
end;
$$;

create or replace function public.clear_admin_login_attempts(p_client_key text)
returns void
language sql
security invoker
set search_path = public
as $$
  delete from public.admin_login_attempts where client_key = p_client_key;
$$;

revoke all on function public.consume_admin_login_attempt(text) from public, anon, authenticated;
revoke all on function public.clear_admin_login_attempts(text) from public, anon, authenticated;
grant execute on function public.consume_admin_login_attempt(text) to service_role;
grant execute on function public.clear_admin_login_attempts(text) to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('portadas', 'portadas', true, 4194304, array['image/jpeg','image/png','image/webp','image/gif']),
  ('canciones', 'canciones', false, 4194304, array['audio/mpeg','audio/mp4','audio/x-m4a','audio/wav','audio/x-wav','audio/ogg','audio/flac'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

commit;
