begin;

alter table public.albums add column if not exists musicbrainz_id uuid;
alter table public.albums add column if not exists release_group_id uuid;
alter table public.albums add column if not exists barcode text;
alter table public.albums add column if not exists label text;
alter table public.albums add column if not exists catalog_number text;
alter table public.albums add column if not exists country text;
alter table public.albums add column if not exists format text;
alter table public.albums add column if not exists metadata_source text;
alter table public.albums add column if not exists cover_rights text not null default 'UNVERIFIED';
alter table public.albums add column if not exists cover_rights_note text;
create unique index if not exists albums_musicbrainz_id_unique on public.albums (musicbrainz_id) where musicbrainz_id is not null;
create index if not exists albums_search_artist_title on public.albums (lower(artist), lower(title));
create index if not exists albums_barcode_idx on public.albums (barcode) where barcode is not null;

create table if not exists public.physical_copies (
  id bigint generated by default as identity primary key,
  album_id bigint not null references public.albums(id) on delete cascade,
  media_condition text,
  sleeve_condition text,
  notes text,
  created_at timestamptz not null default now(),
  constraint physical_copies_media_condition check (media_condition is null or media_condition in ('M','NM','VG+','VG','G+','G','F','P')),
  constraint physical_copies_sleeve_condition check (sleeve_condition is null or sleeve_condition in ('M','NM','VG+','VG','G+','G','F','P')),
  constraint physical_copies_notes_limit check (notes is null or char_length(notes) <= 2000)
);
create index if not exists physical_copies_album_idx on public.physical_copies(album_id);

create table if not exists public.tracks (
  id bigint generated by default as identity primary key,
  album_id bigint not null references public.albums(id) on delete cascade,
  disc_number integer not null default 1 check (disc_number between 1 and 20),
  track_number integer not null check (track_number between 1 and 200),
  position_label text,
  title text not null check (char_length(btrim(title)) between 1 and 300),
  artist text,
  duration_ms integer check (duration_ms is null or duration_ms between 0 and 36000000),
  musicbrainz_recording_id uuid,
  isrc text,
  metadata_source text,
  playback_type text not null default 'NO_AUDIO_AVAILABLE' check (playback_type in ('FULL_AUDIO','OFFICIAL_PLAYER','PREVIEW_ONLY','NO_AUDIO_AVAILABLE')),
  rights_status text not null default 'UNVERIFIED' check (rights_status in ('UNVERIFIED','AUTHORIZED','REVOKED')),
  provider text,
  provider_track_id text,
  playback_url text,
  storage_path text,
  rights_evidence text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(album_id,disc_number,track_number),
  constraint tracks_rights_gate check (
    playback_type = 'NO_AUDIO_AVAILABLE' or
    (rights_status = 'AUTHORIZED' and nullif(btrim(rights_evidence), '') is not null)
  )
);
create index if not exists tracks_album_order_idx on public.tracks(album_id,disc_number,track_number);

create or replace function public.sync_manual_tracks()
returns trigger language plpgsql security invoker set search_path = public as $$
begin
  if new.metadata_source = 'MusicBrainz' then return new; end if;
  if tg_op = 'UPDATE' and new.tracklist is not distinct from old.tracklist then return new; end if;
  if tg_op = 'UPDATE' and exists(select 1 from public.tracks where album_id = new.id and rights_status = 'AUTHORIZED') then
    raise exception 'remove authorized audio before replacing the tracklist';
  end if;
  delete from public.tracks where album_id = new.id;
  insert into public.tracks(album_id,disc_number,track_number,title,artist,metadata_source)
  select new.id,1,ordinality::integer,value,new.artist,'Manual'
    from jsonb_array_elements_text(new.tracklist) with ordinality as t(value,ordinality);
  return new;
end;
$$;
drop trigger if exists albums_sync_manual_tracks on public.albums;
create trigger albums_sync_manual_tracks after insert or update of tracklist on public.albums
  for each row execute function public.sync_manual_tracks();

create or replace function public.initialize_album_copy()
returns trigger language plpgsql security invoker set search_path = public as $$
begin
  insert into public.physical_copies(album_id) values(new.id);
  return new;
end;
$$;
drop trigger if exists albums_initialize_copy on public.albums;
create trigger albums_initialize_copy after insert on public.albums
  for each row execute function public.initialize_album_copy();

insert into public.physical_copies(album_id)
select id from public.albums a where not exists(select 1 from public.physical_copies c where c.album_id = a.id);
insert into public.tracks(album_id,disc_number,track_number,title,artist,metadata_source)
select a.id,1,t.ordinality::integer,t.value,a.artist,'Manual'
  from public.albums a cross join lateral jsonb_array_elements_text(a.tracklist) with ordinality as t(value,ordinality)
  where a.metadata_source is distinct from 'MusicBrainz'
on conflict(album_id,disc_number,track_number) do nothing;

create table if not exists public.music_metadata_cache (
  release_id uuid primary key,
  payload jsonb not null,
  expires_at timestamptz not null,
  refreshed_at timestamptz not null default now()
);
create table if not exists public.external_api_throttle (
  provider text primary key,
  last_call_at timestamptz not null
);

alter table public.physical_copies enable row level security;
alter table public.physical_copies force row level security;
alter table public.tracks enable row level security;
alter table public.tracks force row level security;
alter table public.music_metadata_cache enable row level security;
alter table public.music_metadata_cache force row level security;
alter table public.external_api_throttle enable row level security;
alter table public.external_api_throttle force row level security;
revoke all on public.physical_copies, public.tracks, public.music_metadata_cache, public.external_api_throttle from anon, authenticated;

update storage.buckets set public = false where id = 'canciones';
drop function if exists public.set_album_track_audio(bigint, integer, text);

create or replace function public.reserve_musicbrainz_call()
returns boolean language plpgsql security invoker set search_path = public as $$
declare previous timestamptz;
begin
  perform pg_advisory_xact_lock(78114217);
  select last_call_at into previous from public.external_api_throttle where provider = 'musicbrainz';
  if previous is not null and previous > now() - interval '1 second' then
    return false;
  end if;
  insert into public.external_api_throttle(provider,last_call_at) values ('musicbrainz',now())
    on conflict(provider) do update set last_call_at = excluded.last_call_at;
  return true;
end;
$$;
revoke all on function public.reserve_musicbrainz_call() from public, anon, authenticated;
grant execute on function public.reserve_musicbrainz_call() to service_role;

create or replace function public.import_musicbrainz_release(p_release jsonb)
returns bigint language plpgsql security invoker set search_path = public as $$
declare album_key bigint; item jsonb; expected_count integer;
begin
  if nullif(p_release->>'musicbrainzId','') is null or nullif(p_release->>'title','') is null
    or nullif(p_release->>'artist','') is null then
    raise exception 'invalid release';
  end if;
  expected_count := jsonb_array_length(coalesce(p_release->'tracks','[]'::jsonb));
  if expected_count < 1 or expected_count > 200 then raise exception 'invalid track count'; end if;
  if exists(select 1 from public.albums where musicbrainz_id = (p_release->>'musicbrainzId')::uuid) then
    raise unique_violation using message = 'release already imported';
  end if;
  insert into public.albums(title,artist,year,discos,tracklist,musicbrainz_id,release_group_id,
    barcode,label,catalog_number,country,format,metadata_source)
  values (p_release->>'title',p_release->>'artist',nullif(p_release->>'year','')::integer,
    greatest(1,least(10,coalesce((p_release->>'discCount')::integer,1))),
    (select jsonb_agg(value->>'title' order by ord) from jsonb_array_elements(p_release->'tracks') with ordinality as t(value,ord)),
    (p_release->>'musicbrainzId')::uuid,nullif(p_release->>'releaseGroupId','')::uuid,
    nullif(p_release->>'barcode',''),nullif(p_release->>'label',''),
    nullif(p_release->>'catalogNumber',''),nullif(p_release->>'country',''),
    nullif(p_release->>'format',''),'MusicBrainz') returning id into album_key;
  for item in select value from jsonb_array_elements(p_release->'tracks') as t(value) loop
    insert into public.tracks(album_id,disc_number,track_number,position_label,title,artist,duration_ms,
      musicbrainz_recording_id,isrc,metadata_source)
    values(album_key,(item->>'discNumber')::integer,(item->>'trackNumber')::integer,
      nullif(item->>'positionLabel',''),item->>'title',nullif(item->>'artist',''),
      nullif(item->>'durationMs','')::integer,nullif(item->>'recordingId','')::uuid,
      nullif(item->>'isrc',''),'MusicBrainz');
  end loop;
  return album_key;
end;
$$;
revoke all on function public.import_musicbrainz_release(jsonb) from public, anon, authenticated;
grant execute on function public.import_musicbrainz_release(jsonb) to service_role;

commit;
